# Generated by Django 6.0.3 on 2026-04-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
