# Generated by Django 6.0.3 on 2026-04-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_platform', '0002_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
