# Generated by Django 6.0.3 on 2026-04-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_platform', '0003_platform_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='logo',
            field=models.URLField(default='https://via.placeholder.com/100'),
            preserve_default=False,
        ),
    ]
