# Generated by Django 6.0.3 on 2026-04-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_platform', '0004_platform_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
